### ISSUE TITLE
To add Docs in reStructuredText format (.rst)

### ISSUE THREAD

**Issue by PhysicistSouravDas** [PhysicistSouravDas/dj-gravatar#3]
Currently, the documentation, which is in Markdown (`.md`) format, is useful to generate `README` and description on the PyPI website. For the documentation to be visible on [readthedocs.io], reStructuredText (`.rst`) format is preferred, so that the Sphinx tool can create the documentation.

Markdown format is also supported, but some more configuration has to be done. Either way will work. Follow [this link] to get started with sphinx. The URL for `dj-gravatar`'s readthedocs.io documentation is [dj-gravatar.readthedocs.io].

[readthedocs.io]: https://readthedocs.org/
[this link]: https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html
[dj-gravatar.readthedocs.io]: https://dj-gravatar.readthedocs.io

**Comment by AryanDas20** [comment]
I have started working on this issue.

**Comment by PhysicistSouravDas** [comment]
@AryanDas20 nice! Few small PRs appreciated than one large PR.

**Comment by PhysicistSouravDas** [comment]
@AryanDas20, there are many inconsistencies, which you must have seen in the documentation website. 

Also, the desired theme is _sphinx-rtd-theme_. 
This link will help, [https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html](https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html).

**Comment by PhysicistSouravDas** [comment]
@AryanDas20, PRs #4 #5 #6 addresses this issue. But, the `_build` folder shouldn't be version controlled, they are generated automatically locally or on the server. Add it in `.gitignore`, and also add Docs dependencies (e.g: sphinx) in `requirements.txt` in the `docs/` folder, so that someone working on Docs knows about the dependencies.

So, two more things to do for you:

- [x] Ignoring build files
- [x] Adding `requirements.txt`

**Comment by PhysicistSouravDas** [comment]
Pull Request #7 fixes this issue.
